### ISSUE TITLE
"releases" folder not found.

### ISSUE THREAD

**Issue by thesukantadey** [mzweilin/EvadeML-Zoo#3]
where is the releases folder in this statement curl -sL https://github.com/mzweilin/EvadeML-Zoo/releases/download/v0.1/downloads.tar.gz

**Comment by mzweilin** [comment]
Hi @thesukantadey , the "releases" folder is managed by Github. I can upload assets to a release to get such a link. But I don't have control on the releases folder.

Best,
-Weilin

**Comment by Kirito0816** [comment]
May I ask how to download these folder now? Thank you.
