### ISSUE TITLE
pre-generated adversary examples's original label

### ISSUE THREAD

**Issue by ygaotong11** [mzweilin/EvadeML-Zoo#5]
Hi,

Appreciate your detailed code and tutorial for reproducing the experiments. For the pre-generate adversary examples, is there anyway I can find the original label. I am trying to calculate the SAE, but without original label, I have no idea about which images is successful adversarial examples.

thanks

**Comment by mzweilin** [comment]
Thanks for your interest. You can find the labels here: https://github.com/mzweilin/EvadeML-Zoo/blob/master/main.py#L134
