### ISSUE TITLE
Dependency broken issue

### ISSUE THREAD

**Issue by zedoul** [mzweilin/EvadeML-Zoo#7]
Hi,

Thank you very much for opening such great source code.

I tried to reproduce your paper but found it broken that it is not working any longer with todays cleverhans and keras with example command line.

python main.py --dataset_name MNIST --model_name carlini \
--nb_examples 2000 --balance_sampling \
--attacks "FGSM?eps=0.1;" \
--robustness "none;FeatureSqueezing?squeezer=bit_depth_1;" \
--detection "FeatureSqueezing?squeezers=bit_depth_1,median_filter_2_2&distance_measure=l1&fpr=0.05;"

Can you share us specific keras and cleverhans version that this code depends on?

**Comment by mzweilin** [comment]
Thanks for your interest in our work. The dependency is described in https://github.com/mzweilin/EvadeML-Zoo/blob/master/requirements_gpu.txt
