### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by icofalc** [mzweilin/EvadeML-Zoo#9]
Hi mzweilin, is it possible to use only the defense part, and so without specifying any attacks?

Like with this example:

python3 main.py --dataset_name ImageNet --model_name MobileNet --nb_examples 10 --balance_sampling --detection "FeaturesSqueezing?squeezers=bit_depth_5,median_filter_2_2,non_local_means_color_11_3_4&distance_measure=l1&threshold=1.2128;"

**Comment by mzweilin** [comment]
> Hi mzweilin, is it possible to use only the defense part, and so without specifying any attacks?
> 
> Like with this example:
> 
> python3 main.py --dataset_name ImageNet --model_name MobileNet --nb_examples 10 --balance_sampling --detection "FeaturesSqueezing?squeezers=bit_depth_5,median_filter_2_2,non_local_means_color_11_3_4&distance_measure=l1&threshold=1.2128;"

Hi @icofalc , we didn't have that design in mind. However, our code does calculate false positive rate on legitimate examples, if that's what you're looking for.

**Comment by icofalc** [comment]
Hi @mzweilin , thanks for your reply,
Yes it could be interesting, how do we have to pass the parameters with our modified image database?
Thanks
@icofalc

**Comment by mzweilin** [comment]
> Hi @mzweilin , thanks for your reply,
> Yes it could be interesting, how do we have to pass the parameters with our modified image database?
> Thanks
> @icofalc

I think you can implement a pseudo attack that wouldn't make any change to images, following the more complex attack examples in https://github.com/mzweilin/EvadeML-Zoo/tree/master/attacks . The False Positive Rate should be reliable.

**Comment by icofalc** [comment]
Hi @mzweilin , thank you!!
Issue is closed 😊
